version: '3.8'

services:
  automatic_detect_service:
    build: .
    image: mivo/yolov7-tracker:latest  # Specify the custom image name and tag
    env_file:
      - .env
    command: ["python3", "automatic_detect.py"]
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
