MODEL:
  PRETRAIN_HW_RATIO: 2
  PRETRAIN_CHOICE: "imagenet"
  # PRETRAIN_PATH: '/home/diego/Documents/Weights/Solider/weights_solider_pcdiego/swin_base/transformer_80.pth'
  PRETRAIN_PATH: '/home/diego/Documents/Weights/Solider/swin_base_patch4_window7_224_22k.pth'
  # PRETRAIN_PATH: '/home/diego/Documents/Weights/Solider/swin_base_patch4_window7_224_22kto1k.pth'
  # PRETRAIN_PATH: ''
  METRIC_LOSS_TYPE: "triplet"
  IF_LABELSMOOTH: "off"
  IF_WITH_CENTER: "no"
  NAME: "transformer"
  NO_MARGIN: True 
  ID_LOSS_TYPE: "softmax" 
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: "swin_base_patch4_window7_224"
  STRIDE_SIZE: [16, 16]

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  # PIXEL_MEAN: [0.5, 0.5, 0.5]
  # PIXEL_STD: [0.5, 0.5, 0.5]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('market1501')
  # ROOT_DIR: ('/home/diego/Documents/DataSets/DataSetForSoliderTotal/TOTAL_MODIFIED/') #TOTAL COMBINADO 
  ROOT_DIR: ('/home/diego/Documents/DataSets/TrainingSolider/e_s/') #Entrada Salida
  # ROOT_DIR: ('/home/diego/Documents/DataSets/TrainingSolider/') #Antiguo market1501 todos

DATALOADER:
  SAMPLER: "softmax_triplet"
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: "AdamW"
  MAX_EPOCHS: 160
  BASE_LR: 0.0008
  WARMUP_EPOCHS: 200
  IMS_PER_BATCH: 64
  WARMUP_METHOD: "cosine"
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 6
  EVAL_PERIOD: 20
  WEIGHT_DECAY: 1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: '/home/diego/Documents/Weights/Solider/weights_solider_pcdiego/swin_base/transformer_80.pth'
  WEIGHT: ''
  NECK_FEAT: "before"
  FEAT_NORM: "yes"

OUTPUT_DIR: "./log/market1501/testsss"

OPTIONAL_MSG: Lo mismo pero sin tanta data augment
